image: node:latest
stages:
  - build
  - test
  - deploy

build:
  stage: build
  except: 
    - master
  script:
    - cd backend/
    - npm install
  cache:
    key:
      files:
        - backend/package-lock.json
    paths:
      - backend/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - backend/node_modules/

test:
  stage: test
  except: 
    - master
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
   - build
  script:
   - cd backend/
   - npm install --save --global jest @types/jest supertest mongodb-memory-server
   - npm run test:ci
  cache:
    key:
      files:
        - backend/package-lock.json
    paths:
      - backend/coverage/
  artifacts:
    paths:
      - backend/coverage/
    when: always
    reports:
      junit:
        - backend/junit.xml
      cobertura: backend/coverage/cobertura-coverage.xml

pages:
 stage: deploy
 image: node:17-alpine
 script:
   - cd backend/
   - npm install redoc-cli
   - npm run start:docs
   - mv ./public ../public
 artifacts:
   paths:
     - public
 only:
   - master
