image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
  cache:
    paths:
      - backend/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - backend/node_modules/

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
   - build
  script:
   - yarn test:ci
  cache:
   paths:
     - backend/coverage/
  artifacts:
    paths:
     - backend/coverage/
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: backend/coverage/cobertura-coverage.xml

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir backend/.public
    - cp -r backend/coverage/* .public
    - mv backend/.public backend/public
  artifacts:
    paths:
      - public
  only:
    - master