version: '3'
services:
  
  database:
    image: arm64v8/mongo:4.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME:cristian
      - MONGO_INITDB_ROOT_PASSWORD:cristian
    volumes:
      - my_data:/data/db
 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: cristian
      ME_CONFIG_MONGODB_ADMINPASSWORD: cristian
      ME_CONFIG_MONGODB_URL: mongodb://cristian:cristian@database:27017/

  node-web:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
      - mongo-express
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"

volumes:
  my_data:
