image: node:latest
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd backend/
    - npm install
    - npm install --save --global jest @types/jest supertest

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
   - build
  script:
   - cd backend/
   - npm test