image: node:latest
stages:
  - test

test:
  stage: test
  dependencies:
   - build
  script:
    - cd backend/
    - npm install
    - npm install --save --global jest @types/jest supertest
    - npm test