image: node:latest
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd backend/
    - npm install
  cache:
    paths:
      - backend/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - backend/node_modules/

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
   - build
  script:
   - cd backend/
   - npm install --save --global jest @types/jest supertest mongodb-memory-server
   - npm test:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml